# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vlm_server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vlm_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vlm_server.proto\x12\x10local_vlm_server\"B\n\x10SendImageRequest\x12\x0e\n\x06images\x18\x01 \x03(\t\x12\x13\n\x06prompt\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_prompt\"!\n\x0eSendImageReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32l\n\x15LocalVlmServerService\x12S\n\tSendImage\x12\".local_vlm_server.SendImageRequest\x1a .local_vlm_server.SendImageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vlm_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDIMAGEREQUEST']._serialized_start=38
  _globals['_SENDIMAGEREQUEST']._serialized_end=104
  _globals['_SENDIMAGEREPLY']._serialized_start=106
  _globals['_SENDIMAGEREPLY']._serialized_end=139
  _globals['_LOCALVLMSERVERSERVICE']._serialized_start=141
  _globals['_LOCALVLMSERVERSERVICE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
